### ISSUE TITLE
ArrayIndexOutOfBoundsException: 7 - unknown cause, sorry.

### ISSUE THREAD

**Issue by Dulciphi** [progwml6/Natura#211]
I'm still so lost on this one. I can load other worlds just fine, no problems, however I cannot load this particular world. I've tried disabling all other mods (except the biome mods I need in order to load this world without a different, unrelated crash). I've tried putting it into peaceful to eliminate the possibility of an enderman picking up a Natura block as the cause. .. I don't really know what to try next. The only suspicious thing my untrained eye can see is all the 'item.tile.tripWireSource' entities in the crash report. I don't know what they're from and could well be a red herring. 

If this was just SSP, I'd simply ignore it and carry on, but this came up in testing for a server upgrade. Natura's already on the server, along with the same mods that were loaded when this crash first appeared.

If you need me to try something different, please let me know. Removing Natura's not an option, least of all because I've gone and built my base inside a huge redwood tree. 

---- Minecraft Crash Report ----
// On the bright side, I bought you a teddy bear!

Time: 13/01/15 8:24 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: 7
	at mods.natura.blocks.NBlock.func_149691_a(NBlock.java:51)
	at net.minecraft.block.Block.func_149673_e(Block.java:556)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4445)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)
	at net.minecraft.client.renderer.EntityRenderer.func_78480_b(EntityRenderer.java:1015)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:990)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at mods.natura.blocks.NBlock.func_149691_a(NBlock.java:51)
	at net.minecraft.block.Block.func_149673_e(Block.java:556)
	at net.minecraft.client.renderer.RenderBlocks.func_147793_a(RenderBlocks.java:8227)
	at net.minecraft.client.renderer.RenderBlocks.func_147751_a(RenderBlocks.java:4445)
	at net.minecraft.client.renderer.RenderBlocks.func_147784_q(RenderBlocks.java:4247)
	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:255)
	at net.minecraft.client.renderer.WorldRenderer.func_147892_a(WorldRenderer.java:181)
	at net.minecraft.client.renderer.RenderGlobal.func_72716_a(RenderGlobal.java:1553)
	at net.minecraft.client.renderer.EntityRenderer.func_78471_a(EntityRenderer.java:1187)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Dulciphi'/203, l='MpServer', x=-850.57, y=79.15, z=21.23]]
	Chunk stats: MultiplayerChunkCache: 406, 406
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-228,71,-247), Chunk: (at 12,4,9 in -15,-16; contains blocks -240,0,-256 to -225,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 43173 game time, 59574 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 143 total; [EntityItem['item.tile.tripWireSource'/256, l='MpServer', x=-848.41, y=3.13, z=-39.66], EntityItem['item.tile.tripWireSource'/257, l='MpServer', x=-849.03, y=4.13, z=-40.47], EntityItem['item.tile.tripWireSource'/258, l='MpServer', x=-848.53, y=2.13, z=-38.22], EntityItem['item.tile.tripWireSource'/259, l='MpServer', x=-851.75, y=4.13, z=-40.25], EntityItem['item.tile.tripWireSource'/260, l='MpServer', x=-849.81, y=4.13, z=-40.88], EntityItem['item.tile.tripWireSource'/262, l='MpServer', x=-850.88, y=2.13, z=-38.56], EntityItem['item.tile.tripWireSource'/263, l='MpServer', x=-849.56, y=16.13, z=-37.72], EntityItem['item.tile.tripWireSource'/264, l='MpServer', x=-849.47, y=16.13, z=-38.56], EntityItem['item.tile.flowers2.minersdelight'/266, l='MpServer', x=-912.13, y=1.13, z=3.31], EntityItem['item.item.arrow'/267, l='MpServer', x=-872.78, y=5.13, z=-35.50], EntityItem['item.item.bone'/268, l='MpServer', x=-872.88, y=5.13, z=-34.34], EntityItem['item.tile.tripWireSource'/269, l='MpServer', x=-839.47, y=1.13, z=-41.81], EntityItem['item.tile.tripWireSource'/271, l='MpServer', x=-840.06, y=2.13, z=-39.81], EntityItem['item.tile.tripWireSource'/272, l='MpServer', x=-833.97, y=3.13, z=-33.94], EntityPainting['Painting'/197, l='MpServer', x=-863.94, y=68.00, z=127.00], EntityItem['item.tile.tripWireSource'/274, l='MpServer', x=-836.59, y=8.13, z=-35.31], EntityItem['item.tile.tripWireSource'/275, l='MpServer', x=-839.19, y=1.13, z=-41.81], EntityItem['item.tile.tripWireSource'/277, l='MpServer', x=-839.19, y=1.13, z=-41.81], EntityItem['item.tile.tripWireSource'/278, l='MpServer', x=-839.19, y=1.13, z=-41.81], EntityItem['item.tile.tripWireSource'/279, l='MpServer', x=-839.44, y=2.13, z=-39.03], EntityItem['item.tile.tripWireSource'/280, l='MpServer', x=-839.19, y=1.13, z=-41.81], EntityItem['item.tile.tripWireSource'/282, l='MpServer', x=-840.88, y=12.13, z=-37.25], EntityItem['item.tile.tripWireSource'/283, l='MpServer', x=-837.75, y=12.13, z=-39.59], EntityItem['item.tile.tripWireSource'/287, l='MpServer', x=-846.28, y=14.63, z=-41.53], EntityItem['item.tile.tripWireSource'/290, l='MpServer', x=-839.13, y=2.13, z=-35.13], EntityItem['item.tile.tripWireSource'/291, l='MpServer', x=-839.19, y=1.13, z=-41.81], EntityItem['item.tile.tripWireSource'/292, l='MpServer', x=-834.84, y=3.13, z=-33.09], EntityItem['item.tile.tripWireSource'/293, l='MpServer', x=-833.84, y=2.13, z=-32.13], EntityItem['item.block.sulfur.cloud'/296, l='MpServer', x=-839.19, y=1.13, z=-41.84], EntityItem['item.tile.tripWireSource'/297, l='MpServer', x=-832.66, y=3.13, z=-32.13], EntityItem['item.tile.tripWireSource'/298, l='MpServer', x=-841.25, y=12.13, z=-42.91], EntityItem['item.tile.tripWireSource'/299, l='MpServer', x=-838.13, y=12.13, z=-41.75], EntityItem['item.tile.tripWireSource'/300, l='MpServer', x=-838.03, y=12.13, z=-35.88], EntityItem['item.tile.tripWireSource'/301, l='MpServer', x=-839.19, y=1.13, z=-41.84], EntityItem['item.tile.tripWireSource'/304, l='MpServer', x=-847.31, y=12.13, z=-42.03], EntityItem['item.tile.tripWireSource'/306, l='MpServer', x=-844.88, y=10.13, z=-32.88], EntityItem['item.tile.tripWireSource'/308, l='MpServer', x=-839.19, y=1.13, z=-41.81], EntityItem['item.tile.tripWireSource'/311, l='MpServer', x=-839.88, y=2.13, z=-36.66], EntityItem['item.tile.tripWireSource'/312, l='MpServer', x=-842.88, y=2.13, z=-36.13], EntityItem['item.tile.tripWireSource'/313, l='MpServer', x=-832.13, y=12.13, z=-39.13], EntityItem['item.tile.tripWireSource'/314, l='MpServer', x=-834.53, y=12.13, z=-40.19], EntityItem['item.tile.tripWireSource'/315, l='MpServer', x=-834.34, y=12.13, z=-32.56], EntityItem['item.tile.tripWireSource'/316, l='MpServer', x=-834.09, y=1.13, z=-38.47], EntityItem['item.tile.tripWireSource'/317, l='MpServer', x=-836.22, y=12.13, z=-34.56], EntityItem['item.tile.tripWireSource'/318, l='MpServer', x=-841.25, y=12.13, z=-32.50], EntityItem['item.tile.tripWireSource'/319, l='MpServer', x=-836.06, y=12.13, z=-32.88], EntityItem['item.tile.tripWireSource'/320, l='MpServer', x=-837.75, y=12.13, z=-32.88], EntityItem['item.tile.tripWireSource'/321, l='MpServer', x=-839.03, y=28.13, z=-33.09], EntityItem['item.tile.tripWireSource'/325, l='MpServer', x=-846.03, y=16.13, z=-41.72], EntityItem['item.tile.tripWireSource'/326, l='MpServer', x=-845.28, y=16.13, z=-33.56], EntityItem['item.tile.tripWireSource'/329, l='MpServer', x=-833.44, y=16.13, z=-42.72], EntityItem['item.tile.tripWireSource'/330, l='MpServer', x=-839.34, y=16.13, z=-37.66], EntityItem['item.tile.tripWireSource'/331, l='MpServer', x=-847.22, y=16.13, z=-37.09], EntityItem['item.tile.tripWireSource'/332, l='MpServer', x=-840.56, y=28.13, z=-32.94], EntityItem['item.tile.tripWireSource'/333, l='MpServer', x=-841.09, y=16.13, z=-36.97], EntityItem['item.tile.tripWireSource'/334, l='MpServer', x=-841.72, y=16.13, z=-33.91], EntityItem['item.tile.tripWireSource'/336, l='MpServer', x=-835.38, y=16.13, z=-41.22], EntityItem['item.tile.tripWireSource'/338, l='MpServer', x=-847.75, y=16.13, z=-38.03], EntityItem['item.tile.tripWireSource'/340, l='MpServer', x=-834.00, y=16.13, z=-40.88], EntityItem['item.tile.tripWireSource'/341, l='MpServer', x=-833.38, y=16.13, z=-39.28], EntityItem['item.tile.tripWireSource'/342, l='MpServer', x=-839.78, y=28.13, z=-33.88], EntityItem['item.tile.tripWireSource'/343, l='MpServer', x=-837.16, y=16.13, z=-34.59], EntityItem['item.tile.tripWireSource'/344, l='MpServer', x=-837.97, y=16.13, z=-32.16], EntityItem['item.tile.tripWireSource'/345, l='MpServer', x=-835.97, y=16.13, z=-33.13], EntityItem['item.tile.tripWireSource'/346, l='MpServer', x=-837.09, y=16.13, z=-33.78], EntityItem['item.tile.tripWireSource'/347, l='MpServer', x=-837.13, y=16.13, z=-32.91], EntityItem['item.tile.tripWireSource'/352, l='MpServer', x=-838.91, y=41.13, z=-32.81], EntityItem['item.tile.tripWireSource'/355, l='MpServer', x=-847.28, y=48.13, z=-42.50], EntityItem['item.tile.tripWireSource'/356, l='MpServer', x=-833.31, y=49.78, z=-40.63], EntityItem['item.tile.tripWireSource'/357, l='MpServer', x=-838.88, y=51.13, z=-32.56], EntityItem['item.tile.rail'/358, l='MpServer', x=-795.09, y=5.13, z=0.53], EntityItem['item.tile.rail'/359, l='MpServer', x=-796.88, y=2.13, z=4.13], EntityItem['item.tile.rail'/360, l='MpServer', x=-797.72, y=16.13, z=4.59], EntityItem['item.tile.rail'/361, l='MpServer', x=-795.09, y=2.13, z=5.19], EntityPig['Pig'/362, l='MpServer', x=-830.54, y=71.63, z=67.34], EntityChicken['Chicken'/365, l='MpServer', x=-895.16, y=72.00, z=-47.47], EntityItem['item.tile.tripWireSource'/369, l='MpServer', x=-831.13, y=1.13, z=-33.25], EntityItem['item.tile.tripWireSource'/372, l='MpServer', x=-830.78, y=3.13, z=-38.56], EntityItem['item.tile.tripWireSource'/373, l='MpServer', x=-828.56, y=1.13, z=-41.19], EntityItem['item.tile.tripWireSource'/374, l='MpServer', x=-831.81, y=4.13, z=-38.69], EntityItem['item.tile.tripWireSource'/375, l='MpServer', x=-829.19, y=1.13, z=-36.13], EntityItem['item.tile.tripWireSource'/377, l='MpServer', x=-830.38, y=5.13, z=-42.47], EntityItem['item.tile.tripWireSource'/381, l='MpServer', x=-831.50, y=16.13, z=-41.28], EntityChicken['Chicken'/382, l='MpServer', x=-796.50, y=2.00, z=-7.50], EntitySheep['Sheep'/384, l='MpServer', x=-924.91, y=75.00, z=-36.94], EntityMinecartChest['entity.MinecartChest.name'/386, l='MpServer', x=-790.50, y=27.50, z=-18.50], EntityPig['Pig'/421, l='MpServer', x=-788.78, y=68.00, z=39.50], EntityVillager['Villager'/422, l='MpServer', x=-873.72, y=64.00, z=101.50], EntityClientPlayerMP['Dulciphi'/203, l='MpServer', x=-850.57, y=79.15, z=21.23], EntityVillager['Villager'/177, l='MpServer', x=-893.56, y=66.00, z=10.09], EntityVillager['Villager'/178, l='MpServer', x=-878.22, y=68.00, z=41.63], EntityVillager['Villager'/179, l='MpServer', x=-855.94, y=70.00, z=70.53], EntityVillager['Villager'/180, l='MpServer', x=-856.88, y=70.00, z=76.44], EntityVillager['Villager'/181, l='MpServer', x=-848.31, y=70.00, z=75.50], EntityVillager['Villager'/186, l='MpServer', x=-860.69, y=69.00, z=52.50], EntityVillager['Villager'/195, l='MpServer', x=-890.47, y=66.00, z=42.94], EntityPainting['Painting'/197, l='MpServer', x=-863.94, y=68.00, z=127.00], EntityVillager['Villager'/200, l='MpServer', x=-871.53, y=71.00, z=1.72], EntityItem['item.tile.rail'/204, l='MpServer', x=-856.78, y=5.13, z=16.97], EntityVillager['Villager'/205, l='MpServer', x=-855.50, y=70.00, z=24.75], EntityVillager['Villager'/206, l='MpServer', x=-861.00, y=80.00, z=18.09], EntityItem['item.tile.rail'/207, l='MpServer', x=-840.75, y=5.13, z=30.81], EntityVillager['Villager'/208, l='MpServer', x=-847.72, y=71.00, z=31.66], EntityVillager['Villager'/209, l='MpServer', x=-860.47, y=70.00, z=35.72], EntityItem['item.tile.rail'/210, l='MpServer', x=-842.69, y=4.13, z=34.09], EntityItem['item.tile.torch'/211, l='MpServer', x=-821.81, y=16.13, z=31.25], EntityVillager['Villager'/212, l='MpServer', x=-880.47, y=67.00, z=63.31], EntityIronGolem['Iron Golem'/213, l='MpServer', x=-865.72, y=67.00, z=48.28], EntityMinecartChest['entity.MinecartChest.name'/214, l='MpServer', x=-825.50, y=34.50, z=5.50], EntityMinecartChest['entity.MinecartChest.name'/215, l='MpServer', x=-829.50, y=38.50, z=36.50], EntityVillager['Villager'/216, l='MpServer', x=-819.09, y=68.00, z=36.47], EntityMinecartChest['entity.MinecartChest.name'/217, l='MpServer', x=-838.50, y=38.50, z=56.50], EntityItem['item.tile.tripWireSource'/218, l='MpServer', x=-850.53, y=3.13, z=-30.13], EntityItem['item.tile.tripWireSource'/219, l='MpServer', x=-849.78, y=5.13, z=-30.31], EntityItem['item.tile.rail'/220, l='MpServer', x=-810.88, y=1.13, z=31.25], EntityMinecartChest['entity.MinecartChest.name'/221, l='MpServer', x=-807.50, y=31.50, z=31.50], EntityItem['item.tile.rail'/222, l='MpServer', x=-807.44, y=4.13, z=31.63], EntityItem['item.tile.rail'/223, l='MpServer', x=-834.88, y=2.13, z=-27.53], EntityItem['item.tile.tripWireSource'/224, l='MpServer', x=-846.16, y=5.13, z=-29.81], EntityItem['item.tile.tripWireSource'/225, l='MpServer', x=-835.13, y=8.13, z=-27.28], EntityItem['item.tile.tripWireSource'/226, l='MpServer', x=-833.94, y=4.13, z=-31.19], EntityItem['item.tile.tripWireSource'/227, l='MpServer', x=-836.50, y=2.13, z=-31.59], EntityItem['item.tile.tripWireSource'/228, l='MpServer', x=-845.97, y=10.13, z=-31.59], EntityItem['item.tile.tripWireSource'/230, l='MpServer', x=-841.72, y=4.13, z=-29.28], EntityItem['item.tile.tripWireSource'/231, l='MpServer', x=-840.78, y=2.13, z=-27.13], EntityItem['item.tile.tripWireSource'/232, l='MpServer', x=-845.53, y=4.13, z=-30.09], EntityItem['item.tile.tripWireSource'/233, l='MpServer', x=-834.88, y=2.13, z=-27.53], EntityItem['item.tile.tripWireSource'/234, l='MpServer', x=-835.13, y=3.13, z=-31.78], EntityItem['item.tile.tripWireSource'/235, l='MpServer', x=-837.28, y=8.13, z=-31.81], EntityItem['item.tile.tripWireSource'/236, l='MpServer', x=-834.88, y=3.13, z=-29.13], EntityItem['item.tile.rail'/237, l='MpServer', x=-841.22, y=16.13, z=-30.13], EntityItem['item.tile.rail'/238, l='MpServer', x=-842.91, y=16.13, z=-29.75], EntityItem['item.tile.tripWireSource'/239, l='MpServer', x=-841.53, y=16.13, z=-31.47], EntityItem['item.tile.tripWireSource'/240, l='MpServer', x=-842.94, y=4.13, z=-30.88], EntityItem['item.tile.tripWireSource'/242, l='MpServer', x=-838.44, y=41.13, z=-30.81], EntityItem['item.tile.rail'/244, l='MpServer', x=-811.94, y=4.13, z=34.66], EntityMinecartChest['entity.MinecartChest.name'/245, l='MpServer', x=-814.50, y=42.50, z=38.50], EntityVillager['Villager'/247, l='MpServer', x=-900.59, y=67.00, z=59.06], EntityMinecartChest['entity.MinecartChest.name'/248, l='MpServer', x=-818.50, y=38.50, z=-24.50], EntityPig['Pig'/249, l='MpServer', x=-806.09, y=64.00, z=-20.84], EntityItem['item.tile.tripWireSource'/250, l='MpServer', x=-850.81, y=2.13, z=-41.88], EntityItem['item.tile.tripWireSource'/253, l='MpServer', x=-843.99, y=1.13, z=-42.22], EntityItem['item.tile.tripWireSource'/255, l='MpServer', x=-849.09, y=5.13, z=-37.75]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2433)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:916)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:286)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:376)
	at org.multimc.EntryPoint.listen(EntryPoint.java:165)
	at org.multimc.EntryPoint.main(EntryPoint.java:54)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3644709008 bytes (3475 MB) / 4260102144 bytes (4062 MB) up to 4260102144 bytes (4062 MB)
	Mod Pack: Unknown / None
	LiteLoader Mods: 1 loaded mod(s)
          - MAtmos version r28 for 1.7.10
	LaunchWrapper: 27 active transformer(s)
          - Transformer: cpw.mods.fml.common.asm.transformers.PatchingTransformer
          - Transformer: com.mumfrey.liteloader.transformers.event.EventProxyTransformer
          - Transformer: com.mumfrey.liteloader.launch.LiteLoaderTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.CrashReportTransformer
          - Transformer: squeek.applecore.asm.TransformerModuleHandler
          - Transformer: cpw.mods.fml.common.asm.transformers.MarkerTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.SideTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.EventSubscriptionTransformer
          - Transformer: codechicken.lib.asm.ClassHeirachyManager
          - Transformer: codechicken.core.asm.InterfaceDependancyTransformer
          - Transformer: codechicken.core.asm.TweakTransformer
          - Transformer: codechicken.core.asm.DelegatedTransformer
          - Transformer: codechicken.core.asm.DefaultImplementationTransformer
          - Transformer: fastcraft.asm.FastCraftTransformer
          - Transformer: mcp.mobius.mobiuscore.asm.CoreTransformer
          - Transformer: openeye.asm.MultiTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.DeobfuscationTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.AccessTransformer
          - Transformer: net.minecraftforge.transformers.ForgeAccessTransformer
          - Transformer: codechicken.core.asm.CodeChickenAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAccessTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ItemStackTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.TerminalTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.LiteLoaderEventInjectionTransformer
          - Transformer: com.mumfrey.liteloader.client.transformers.MinecraftOverlayTransformer
          - Transformer: com.mumfrey.liteloader.common.transformers.LiteLoaderPacketTransformer
          - Transformer: cpw.mods.fml.common.asm.transformers.ModAPITransformer
	JVM Flags: 9 total; -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+CICompilerCountPerCPU -XX:+TieredCompilation -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx4096m -XX:PermSize=512m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 13, tcache: 7, allocated: 1, tallocated: 34
	FML: MCP v9.05 FML v7.10.85.1240 Minecraft Forge 10.13.2.1240 22 mods loaded, 22 mods active
	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FML{7.10.85.1240} [Forge Mod Loader] (forge-1.7.10-10.13.2.1240-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Forge{10.13.2.1240} [Minecraft Forge] (forge-1.7.10-10.13.2.1240-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	CodeChickenCore{1.0.4.29} [CodeChicken Core] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MobiusCore{1.2.3} [MobiusCore] (minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	OpenEye{0.6} [OpenEye] (OpenEye-0.6-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	AppleCore{1.0.2} [AppleCore] (AppleCore-mc1.7.10-1.0.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle{1.7.10-0.3.2.jenkins184} [Mantle] (Mantle-1.7.10-0.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.0.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.1034-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	climatecontrol{0.4} [Climate Control] (ClimateControl-0.4.beta14.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	FastCraft{1.12} [FastCraft] (fastcraft-1.12.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Highlands{2.2.2} [Highlands] (Highlands-1.7.2-v-2.2.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MineTweaker3{3.0.9B} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.9C.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MapWriter{2.1.1} [MapWriter] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Opis{1.2.3} [Opis] (Opis-1.2.3_1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	VersionChecker{1.1.7} [Version Checker] (VersionChecker-1.1.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMultipart{1.1.1.320} [Forge Multipart] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	McMultipart{1.1.1.320} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	MrTJPCoreMod{1.0} [MrTJPCoreMod] (MrTJPCore-1.7.10-1.0.3.5-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	ForgeMicroblock{1.1.1.320} [Forge Microblocks] (ForgeMultipart-1.7.10-1.1.1.320-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
	Mantle Environment: Environment healthy.
	Launched Version: 1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce GTX 760/PCIe/SSE2 GL version 4.5.0 NVIDIA 347.09, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: [msi_conversion.zip, MisaModded.zip]
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Dulciphi** [comment]
well.. there was indeed a butt-ton of trip-wires. I removed Natura - and the stone and went to the co-ords and had a look. Whatever it was that created an entire column of tripwires underground, it wasn't Natura. If anything, Natura helped alert me to Enviromine doing something ...well ..I don't know what it was doing lol.

![2015-01-13_21 34 50](https://cloud.githubusercontent.com/assets/7909813/5721027/f6ca68aa-9b77-11e4-84bd-0fba9d5b4466.png)

Hmm.. a shaft full of tripwires ..or my Natura treehouse base. Decisions decisions :P
