### ISSUE TITLE
[1.7.10] Creating new world crash.

### ISSUE THREAD

**Issue by FrostySigh** [progwml6/Natura#222]
I have tried to remove the mods that it says it might be and it didn't work but when I removed Natura it stopped crashing, don't know what is causing it.

Here is the crash-log:

http://openeye.openmods.info/crashes/7f61350f2576bff0fb9b09c778d823e6

(Hope this is the right mod that is causing it)

**Comment by TherminatorX** [comment]
Can we have the crashlog that only blames Natura?

**Comment by FrostySigh** [comment]
Hmmm, after some more testing it seams like it is some of the other mods that I have installed that is causing a conflict with Natura, maybe there is a update for that/those mod/s, I'll see if there is any... 

(I'm guessing it is either Railcraft or malisis core)

(will write if I get it fixed if anyone else have the same problem)

**Comment by FrostySigh** [comment]
It is a conflict or something with Railcraft version 9.5.0.0 and Natura version 2.2.0.1, it seams like both mods are trying to add stuff to the world at the same time or something?

**Comment by usafphoenix** [comment]
does crash happen with railcraft 9.7.0.0?

**Comment by trismegistis** [comment]
Hi! I have a similar crash on our server with 2.2.0.1 - 

[FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ServerTickEvent@1d1622f1:
net.minecraft.util.ReportedException: Exception getting block type in world
        at net.minecraft.world.World.func_147439_a(World.java:354) ~[ahb.class:?]
        at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
        at mods.natura.worldgen.BaseCropWorldgen.generateBluebells(BaseCropWorldgen.java:179) ~[BaseCropWorldgen.class:?]
        at mods.natura.worldgen.BaseCropWorldgen.generate(BaseCropWorldgen.java:60) ~[BaseCropWorldgen.class:?]
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) ~[GameRegistry.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050) ~[apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
        at net.shadowmage.ancientwarfare.structure.town.TownPlacementValidator.isAverageHeightWithin(TownPlacementValidator.java:186) ~[TownPlacementValidator.class:?]
        at net.shadowmage.ancientwarfare.structure.town.TownPlacementValidator.tryExpandZPos(TownPlacementValidator.java:177) ~[TownPlacementValidator.class:?]
        at net.shadowmage.ancientwarfare.structure.town.TownPlacementValidator.expandBoundingArea(TownPlacementValidator.java:134) ~[TownPlacementValidator.class:?]
        at net.shadowmage.ancientwarfare.structure.town.TownPlacementValidator.findGenerationPosition(TownPlacementValidator.java:62) ~[TownPlacementValidator.class:?]
        at net.shadowmage.ancientwarfare.structure.town.WorldTownGenerator.attemptGeneration(WorldTownGenerator.java:38) ~[WorldTownGenerator.class:?]
        at net.shadowmage.ancientwarfare.structure.world_gen.WorldGenTickHandler.genTowns(WorldGenTickHandler.java:80) ~[WorldGenTickHandler.class:?]
        at net.shadowmage.ancientwarfare.structure.world_gen.WorldGenTickHandler.serverTick(WorldGenTickHandler.java:50) ~[WorldGenTickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_105_WorldGenTickHandler_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) [EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) [FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) [MinecraftServer.class:?]
        at fastcraft.K.a(F:21) [fastcraft-1.22-ctest14.jar:?]
        at fastcraft.H.aq(F:157) [fastcraft-1.22-ctest14.jar:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.IllegalArgumentException
        at net.minecraft.util.WeightedRandom.func_76273_a(WeightedRandom.java:28) ~[qv.class:?]
        at net.minecraft.util.WeightedRandom.func_76271_a(WeightedRandom.java:60) ~[qv.class:?]
        at net.minecraft.world.SpawnerAnimals.func_77191_a(SpawnerAnimals.java:235) ~[aho.class:?]
        at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:424) ~[aqz.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) ~[apx.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
        ... 27 more
[21:39:37] [Server thread/ERROR] [FML]: Index: 4 Listeners:
[21:39:37] [Server thread/ERROR] [FML]: 0: NORMAL
[21:39:37] [Server thread/ERROR] [FML]: 1: ASM: am2.proxy.tick.ServerTickHandler@3526df55 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 2: ASM: ic2.core.TickHandler@6d6b7b6 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 3: ASM: net.shadowmage.ancientwarfare.automation.gamedata.MailboxTicker@58fdcc65 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 4: ASM: net.shadowmage.ancientwarfare.structure.world_gen.WorldGenTickHandler@4ecad287 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 5: ASM: us.ichun.mods.ichunutil.common.core.TickHandlerServer@c309360 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 6: ASM: chylex.hee.mechanics.charms.handler.CharmPouchHandler@795bcbc1 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 7: ASM: chylex.hee.mechanics.misc.TempleEvents@3baee147 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 8: ASM: com.brandon3055.brandonscore.common.handlers.ProcessHandler@12cd8cca onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 9: ASM: mods.railcraft.client.sounds.SoundLimiterTicker@7c41f2b0 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 10: ASM: de.npe.gameanalytics.minecraft.ActivityReportTickEventHandler@7b55a11f serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 11: ASM: crazypants.enderio.machine.spawner.BlockPoweredSpawner@35f97949 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 12: ASM: crazypants.enderio.conduit.ConduitNetworkTickHandler@5334889e onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 13: ASM: net.dries007.holoInventory.util.Metrics@e24a830 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 14: ASM: hardcorequesting.EventHandler@2f8bc375 onEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 15: ASM: hardcorequesting.quests.QuestTicker@6c71bd1 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 16: ASM: com.emoniph.witchery.common.ServerTickEvents@22de040b onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 17: ASM: buildcraft.core.tablet.manager.TabletManagerServer@f22141a serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 18: ASM: aroma1997.backup.EventListener@60eb3ace tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 19: ASM: GridTickHandler[Energy]@1013458644 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 20: ASM: GridTickHandler[Redstone]@2019779209 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 21: ASM: GridTickHandler[Fluid]@366617874 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 22: ASM: powercrystals.minefactoryreloaded.net.ConnectionHandler@823e30b tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 23: ASM: dan200.computercraft.shared.proxy.ComputerCraftProxyCommon$ForgeHandlers@27281a27 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 24: ASM: li.cil.oc.common.EventHandler$@34a62c53 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)Ljava/lang/Object;
[21:39:37] [Server thread/ERROR] [FML]: 25: ASM: li.cil.oc.common.asm.SimpleComponentTickHandler@79e539c0 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 26: ASM: li.cil.oc.common.item.Tablet$@6250bcb8 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 27: ASM: build.EventHandlerFML@1b949230 tickServer(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 28: ASM: CoroPets.EventHandlerFML@44967e35 tickServer(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 29: ASM: CoroUtil.forge.EventHandlerFML@1d727136 tickServer(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 30: ASM: com.enderio.core.common.util.Scheduler@253b98c3 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 31: ASM: Network Registry:
[] onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 32: ASM: crazypants.enderio.CommonProxy$TickTimer@5cfdf26a onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 33: ASM: thaumic.tinkerer.common.potion.PotionEffectHandler@3bd78533 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 34: ASM: HxCKDMS.HxCCore.Events.EventNickSync@47d1c18d onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 35: ASM: HxCKDMS.HxCCore.Events.EventTpRequest@42920be5 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 36: ASM: INSTANCE tickServer(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 37: ASM: openblocks.common.ServerTickHandler@6aba76b0 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 38: ASM: mcjty.rftools.dimension.DimensionTickEvent@25ae0e95 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 39: ASM: cofh.thermaldynamics.core.TickHandler@5ed11f81 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 40: ASM: torched.common.core.TickHandlerServer@186652ec onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 41: ASM: codechicken.multipart.handler.MultipartEventHandler$@445c9a5e serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 42: ASM: com.rwtema.extrautils.CommandTPSTimer@322be71a onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 43: ASM: com.forgeessentials.core.misc.TaskRegistry@1eb96c98 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 44: ASM: com.forgeessentials.core.misc.TeleportHelper@3a3fad9 serverTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 45: ASM: com.forgeessentials.util.questioner.Questioner@5a5a2465 tickStart(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 46: ASM: com.forgeessentials.multiworld.MultiworldManager@5e4c80f5 serverTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 47: ASM: com.forgeessentials.worldborder.ModuleWorldBorder@5b7a9237 serverTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 48: ASM: com.forgeessentials.permissions.core.ZonedPermissionHelper@1cc10ec9 serverTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 49: ASM: com.forgeessentials.permissions.core.PermissionScheduler@25e1e1a1 serverTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 50: ASM: com.forgeessentials.protection.ProtectionEventHandler@5b2994bd serverTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 51: ASM: riskyken.armourersWorkshop.common.skin.SkinDataCache@484d885a onServerTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 52: ASM: com.forgeessentials.core.mcstats.Metrics@44ca4e8b tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 53: ASM: vazkii.botania.common.block.BlockPistonRelay@2120ff7e tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 54: ASM: org.dave.CompactMachines.handler.CMTickHandler@755edd07 tick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 55: ASM: lumien.randomthings.Handler.RTTickHandler@46adcfbd tick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 56: ASM: remoteio.common.tracker.BlockTracker@7de52e58 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 57: ASM: ivorius.yegamolchattels.events.YGCFMLEventHandler@57d85508 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[21:39:37] [Server thread/ERROR] [FML]: 58: ASM: appeng.hooks.TickHandler@61f8ecc4 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
[21:39:37] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception getting block type in world
        at net.minecraft.world.World.func_147439_a(World.java:354) ~[ahb.class:?]
        at net.minecraft.world.World.func_147437_c(World.java:365) ~[ahb.class:?]
        at mods.natura.worldgen.BaseCropWorldgen.generateBluebells(BaseCropWorldgen.java:179) ~[BaseCropWorldgen.class:?]
        at mods.natura.worldgen.BaseCropWorldgen.generate(BaseCropWorldgen.java:60) ~[BaseCropWorldgen.class:?]
        at cpw.mods.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:112) ~[GameRegistry.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:280) ~[ms.class:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050) ~[apx.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
        at net.shadowmage.ancientwarfare.structure.town.TownPlacementValidator.isAverageHeightWithin(TownPlacementValidator.java:186) ~[TownPlacementValidator.class:?]
        at net.shadowmage.ancientwarfare.structure.town.TownPlacementValidator.tryExpandZPos(TownPlacementValidator.java:177) ~[TownPlacementValidator.class:?]
        at net.shadowmage.ancientwarfare.structure.town.TownPlacementValidator.expandBoundingArea(TownPlacementValidator.java:134) ~[TownPlacementValidator.class:?]
        at net.shadowmage.ancientwarfare.structure.town.TownPlacementValidator.findGenerationPosition(TownPlacementValidator.java:62) ~[TownPlacementValidator.class:?]
        at net.shadowmage.ancientwarfare.structure.town.WorldTownGenerator.attemptGeneration(WorldTownGenerator.java:38) ~[WorldTownGenerator.class:?]
        at net.shadowmage.ancientwarfare.structure.world_gen.WorldGenTickHandler.genTowns(WorldGenTickHandler.java:80) ~[WorldGenTickHandler.class:?]
        at net.shadowmage.ancientwarfare.structure.world_gen.WorldGenTickHandler.serverTick(WorldGenTickHandler.java:50) ~[WorldGenTickHandler.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_105_WorldGenTickHandler_serverTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:396) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
Caused by: java.lang.IllegalArgumentException
        at net.minecraft.util.WeightedRandom.func_76273_a(WeightedRandom.java:28) ~[qv.class:?]
        at net.minecraft.util.WeightedRandom.func_76271_a(WeightedRandom.java:60) ~[qv.class:?]
        at net.minecraft.world.SpawnerAnimals.func_77191_a(SpawnerAnimals.java:235) ~[aho.class:?]
        at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:424) ~[aqz.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279) ~[ms.class:?]
        at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1045) ~[apx.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:52) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:12) ~[ChunkIOProvider.class:?]
        at net.minecraftforge.common.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:344) ~[AsynchronousExecutor.class:?]
        at net.minecraftforge.common.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:302) ~[AsynchronousExecutor.class:?]
        at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:12) ~[ChunkIOExecutor.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:126) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101) ~[ms.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199) ~[ms.class:?]
        at net.minecraft.world.World.func_72964_e(World.java:419) ~[ahb.class:?]
        at net.minecraft.world.World.func_147439_a(World.java:345) ~[ahb.class:?]
        ... 25 more

**Comment by trismegistis** [comment]
and BTW. you guys make it really hard to trace this down. It could be both mods conflicts, but neither of yours would tell me either was a culprit until I used /pregen instead of going to the chunk -.- When going to the chunk all it would do is say generic crash information and no trace to any mod. Please use better debugging techniques I could have fixed this weeks ago myself :|

**Comment by rob-bb** [comment]
Pretty much the same, I also have Railcraft 9.7.00 so I will look into that.

**Comment by progwml6** [comment]
1.7 is no longer being updated. Feel free to submit a PR.
