### ISSUE TITLE
[1.10.2-4.0.0.76] Tree/Chunk Loading Error

### ISSUE THREAD

**Issue by davidgarland** [progwml6/Natura#286]
Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  SHLoadingPlugin (ScalingHealth-1.9.4-0.2.2-20 (1).jar)
  FMLPlugin (InventoryTweaks-1.61-58 (2).jar)
  IvToolkit (IvToolkit-1.2.8.5.jar)
  NWRTweak (redstonepaste-mc1.9.4-1.7.4 (2).jar)
  LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  SurgeLoadingPlugin (Surge-1.10.2-1.0.0.50 (4).jar)
  BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.1.319.jar)
  ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 9/26/16 9:23 PM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyAnyInteger{name=variation, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockStateContainer{block=minecraft:dirt, properties=[snowy, variant]}
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
    at team.chisel.common.block.BlockCarvable.func_176201_c(BlockCarvable.java:160)
    at team.chisel.common.block.BlockCarvable.func_149662_c(BlockCarvable.java:254)
    at com.progwml6.natura.world.worldgen.trees.overworld.EucalyptusTreeGenerator.findGround(EucalyptusTreeGenerator.java:94)
    at com.progwml6.natura.world.worldgen.trees.overworld.EucalyptusTreeGenerator.generateTree(EucalyptusTreeGenerator.java:54)
    at com.progwml6.natura.world.worldgen.TreeGenerator.generateOverworld(TreeGenerator.java:166)
    at com.progwml6.natura.world.worldgen.TreeGenerator.generate(TreeGenerator.java:79)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Thread: Client thread
Stacktrace:
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:196)
    at team.chisel.common.block.BlockCarvable.func_176201_c(BlockCarvable.java:160)
    at team.chisel.common.block.BlockCarvable.func_149662_c(BlockCarvable.java:254)
    at com.progwml6.natura.world.worldgen.trees.overworld.EucalyptusTreeGenerator.findGround(EucalyptusTreeGenerator.java:94)
    at com.progwml6.natura.world.worldgen.trees.overworld.EucalyptusTreeGenerator.generateTree(EucalyptusTreeGenerator.java:54)
    at com.progwml6.natura.world.worldgen.TreeGenerator.generateOverworld(TreeGenerator.java:166)
    at com.progwml6.natura.world.worldgen.TreeGenerator.generate(TreeGenerator.java:79)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120)
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001)
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:964)
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154)
    at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
    at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
    at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:222)

-- Affected level --
Details:
    Level name: Silica
    All players: 1 total; [EntityPlayerMP['<PROFILE NAME>'/7119, l='Silica', x=76.57, y=84.00, z=125.87]]
    Chunk stats: ServerChunkCache: 777 Drop: 0
    Level seed: 1995422030
    Level generator: ID 06 - quark_realistic, ver 0. Features enabled: true
    Level generator options: 
    Level spawn location: World: (-48,64,256), Chunk: (at 0,4,0 in -3,16; contains blocks -48,0,256 to -33,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
    Level time: 701 game time, 701 day time
    Level dimension: 0
    Level storage version: 0x04ABD - Anvil
    Level weather: Rain time: 84111 (now: false), thunder time: 135105 (now: false)
    Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:698)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
    at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:149)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
    at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Mac OS X (x86_64) version 10.11.6
    Java Version: 1.8.0_91, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1434352200 bytes (1367 MB) / 3857186816 bytes (3678 MB) up to 5592580096 bytes (5333 MB)
    JVM Flags: 2 total; -Xms2048m -Xmx6000m
    IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
    FML: MCP 9.32 Powered by Forge 12.18.1.2077 85 mods loaded, 85 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UCHIJAAAAAAAAAAAAAA mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UCHIJAAAAAAAAAAAAAA FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2077-universal.jar) 
    UCHIJAAAAAAAAAAAAAA Forge{12.18.1.2077} [Minecraft Forge](forge-1.10.2-12.18.1.2077-universal.jar) 
    UCHIJAAAAAAAAAAAAAA ivtoolkit{1.2.8.5} [IvToolkit](minecraft.jar) 
    UCHIJAAAAAAAAAAAAAA fenceoverhaul{1.2.1} [Fence Overhaul]([1.10.x]FenceOverhaul-1.2.1.jar) 
    UCHIJAAAAAAAAAAAAAA alt{1.06} [Additional Loot Tables](AdditionalLootTables_1.10.2-1.06.jar) 
    UCHIJAAAAAAAAAAAAAA aquaculture{1.4.0} [Aquaculture](Aquaculture-1.10.2-1.4.0.28.jar) 
    UCHIJAAAAAAAAAAAAAA ArrowFix{1.1} [Tipped Arrow Fixer](ArrowFix-1.1 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA Quark{r1.0-56} [Quark](Quark-r1.0-56.jar) 
    UCHIJAAAAAAAAAAAAAA AutoRegLib{1.0-2} [AutoRegLib](AutoRegLib-1.0-2 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA backpack{3.0.1} [Backpack](backpack-3.0.1-1.10.2.jar) 
    UCHIJAAAAAAAAAAAAAA bagginses{2.4.2d} [Bagginses](Bagginses-1.10.2-3.0.4b.jar) 
    UCHIJAAAAAAAAAAAAAA Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0 %282%29.jar) 
    UCHIJAAAAAAAAAAAAAA mantle{1.10.2-1.0.0.jenkins170} [Mantle](Mantle-1.10.2-1.0.0 %282%29.jar) 
    UCHIJAAAAAAAAAAAAAA natura{unspecified} [Natura](natura-1.10.2-4.0.0.76 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA betterwithmods{0.11 Beta hotfix 2} [Better With Mods](Better With Mods-0.11-1.10.2-hotfix2.jar) 
    UCHIJAAAAAAAAAAAAAA BetterHorseHud{1.0} [Better Horse Hud](BetterHorseHud-[1.9-1.10.2]-1.0.jar) 
    UCHIJAAAAAAAAAAAAAA Bloodmoon{1.2} [Bloodmoon](Bloodmoon-MC1.9.4-1.4.1.jar) 
    UCHIJAAAAAAAAAAAAAA infinitylib{1.10.2-@MAJOR@.@MINOR@.@REVIS@} [InfinityLib](infinityLib-0.1.jar) 
    UCHIJAAAAAAAAAAAAAA boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull](boatifull-0.1 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA bookshelf{1.4.1.319} [Bookshelf](Bookshelf-1.10.2-1.4.1.319.jar) 
    UCHIJAAAAAAAAAAAAAA Bullseye{1.0.3} [Bullseye](Bullseye-1.9.4-1.0.3 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA ceramics{1.10.2-1.0.0} [Ceramics](Ceramics-1.10.2-1.0.0.jar) 
    UCHIJAAAAAAAAAAAAAA Chameleon{1.10-2.1.7} [Chameleon](Chameleon-1.10-2.1.7 %282%29.jar) 
    UCHIJAAAAAAAAAAAAAA chisel{MC1.9.4-0.0.6.33} [Chisel](Chisel-MC1.9.4-0.0.6.33 %283%29.jar) 
    UCHIJAAAAAAAAAAAAAA chiselsandbits{12.1} [Chisels & Bits](chiselsandbits-12.1 %283%29.jar) 
    UCHIJAAAAAAAAAAAAAA compasscoords{1.10.2-3.1.7} [Compass Co-ords](CompassCoords-1.10.2-3.1.7.jar) 
    UCHIJAAAAAAAAAAAAAA coralreef{1.0} [Coral Reef](CoralReef-1.2 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA cosmeticarmorreworked{1.10.2-v1a} [CosmeticArmorReworked](CosmeticArmorReworked-1.10.2-v1a %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA craftingtweaks{6.1.12} [Crafting Tweaks](CraftingTweaks_1.10.2-6.1.12.jar) 
    UCHIJAAAAAAAAAAAAAA cyclopscore{0.7.7} [Cyclops Core](CyclopsCore-1.9.4-0.7.7 %284%29.jar) 
    UCHIJAAAAAAAAAAAAAA Ding{MC1.9.0v2} [Ding](Ding-1.10.2-1.0.0.jar) 
    UCHIJAAAAAAAAAAAAAA double_jump{1.0.1} [DoubleJump](DoubleJump-1.10.2-1.0.0.jar) 
    UCHIJAAAAAAAAAAAAAA DungeonTactics{DT0.9.5} [DungeonTactics](DungeonTactics-1.10.2-0.9.5.jar) 
    UCHIJAAAAAAAAAAAAAA dsurroundunofficial{3.0.6.1BETA} [Dynamic Surroundings Unofficial](DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar) 
    UCHIJAAAAAAAAAAAAAA easyBreeding{5.0.0} [Easy Breeding](easybreeding-1.9.4-4.0.1.jar) 
    UCHIJAAAAAAAAAAAAAA elevatorid{1.0.0} [Elevator Mod](ElevatorMod[V.1.0.0][MC.1.10.2].jar) 
    UCHIJAAAAAAAAAAAAAA eplus{4.1.0.102} [Enchanting Plus](EnchantingPlus-1.10.2-4.1.0.108.jar) 
    UCHIJAAAAAAAAAAAAAA enderthing{0.6.11} [Enderthing](enderthing-1.10.2-0.6.11.jar) 
    UCHIJAAAAAAAAAAAAAA extraalchemy{0.3.0.1-beta} [Extra Alchemy](extraalchemy-0.3.0.1-beta.jar) 
    UCHIJAAAAAAAAAAAAAA shadowmc{3.4.4} [ShadowMC](ShadowMC-1.10.2-3.4.4 %282%29.jar) 
    UCHIJAAAAAAAAAAAAAA ExtraRails{1.1.1} [Extra Rails](ExtraRails-1.10.2-1.1.1.jar) 
    UCHIJAAAAAAAAAAAAAA gravestone{1.5.5} [Gravestone](GraveStone Mod 1.5.5.jar) 
    UCHIJAAAAAAAAAAAAAA HardcoreDarkness{1.8} [Hardcore Darkness](HardcoreDarkness-MC1.9.4-1.8.jar) 
    UCHIJAAAAAAAAAAAAAA hopperducts{1.4.7} [Hopper Ducts](hopperducts-mc1.9.4-1.4.7 %282%29.jar) 
    UCHIJAAAAAAAAAAAAAA inventorysorter{0.10.0+42} [Simple Inventory sorting](inventorysorter-1.10-0.10.0+42.jar) 
    UCHIJAAAAAAAAAAAAAA inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks](InventoryTweaks-1.61-58 %282%29.jar) 
    UCHIJAAAAAAAAAAAAAA JEI{3.10.0.267} [Just Enough Items](jei_1.10.2-3.10.0.267.jar) 
    UCHIJAAAAAAAAAAAAAA jlgm_chatbox{1.10.2-0.4.0-hotfix} [Chat Box](jlgm_chatbox-1.10.2-0.4.0-hotfix.jar) 
    UCHIJAAAAAAAAAAAAAA jeresources{0.5.2.57} [Just Enough Resources](JustEnoughResources-1.10.2-0.5.2.57.jar) 
    UCHIJAAAAAAAAAAAAAA levels{r4.1.3} [Levels](Levels-1.10.2-r4.1.3 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA llor{1.1.0-mc[1.9-1.10.2]} [Light Level Overlay Reloaded](LLOverlayReloaded-1.1.0-mc[1.9-1.10.2].jar) 
    UCHIJAAAAAAAAAAAAAA lootbags{2.1.2} [Loot Bags](LootBags-1.10.2-2.1.2.jar) 
    UCHIJAAAAAAAAAAAAAA testdummy{1.11} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.11 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA ModNameTooltip{1.6.0} [Mod Name Tooltip](modnametooltip_1.10.2-1.6.0.jar) 
    UCHIJAAAAAAAAAAAAAA Morpheus{1.10.2-3.1.7} [Morpheus](Morpheus-1.10.2-3.1.7 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA Neat{1.3-12} [Neat](Neat 1.3-12.jar) 
    UCHIJAAAAAAAAAAAAAA nethercore{1.10.2-2.0.2} [Nether Core](nethercore-1.10.2-2.0.2.jar) 
    UCHIJAAAAAAAAAAAAAA netherportalfix{1.0} [Nether Portal Fix](netherportalfix-mc1.9.4-4.0.1.jar) 
    UCHIJAAAAAAAAAAAAAA nmsot{1.1.7-mc[1.9.4-1.10.2]} [No Mob Spawning on Trees](NoMobSpawningOnTrees-1.1.7-mc[1.9.4-1.10.2].jar) 
    UCHIJAAAAAAAAAAAAAA samsocean{1.0.0} [Classic Oceans](OceanFloor-1.10.2-1.0.1.jar) 
    UCHIJAAAAAAAAAAAAAA packetfilter{1.0.2} [Packet Filter](packetfilter-1.0.2.jar) 
    UCHIJAAAAAAAAAAAAAA packingtape{0.6.0} [Packing Tape](PackingTape-1.10.2-0.6.0.jar) 
    UCHIJAAAAAAAAAAAAAA PersistentBits{1.0.4} [Persistent Bits](PersistentBits-1.10.2-1.0.4 %282%29.jar) 
    UCHIJAAAAAAAAAAAAAA ping{1.2.2} [Ping](Ping-1.10.X-1.2.2.B7-universal %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA gunpowder{1.1_1.9.4} [Placeable Gunpowder](PlaceableGunpowder-1.1_1.9.4.jar) 
    UCHIJAAAAAAAAAAAAAA samsapples{1.1.5} [Power Apples](PowerApples-1.10.2-1.1.5 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA reccomplex{1.1.1} [Recurrent Complex](RecurrentComplex-1.1.1.jar) 
    UCHIJAAAAAAAAAAAAAA redstonepaste{1.7.4} [Redstone Paste](redstonepaste-mc1.9.4-1.7.4 %282%29.jar) 
    UCHIJAAAAAAAAAAAAAA Roguelike{1.5.4} [Roguelike Dungeons](RoguelikeDungeons-1.10.2-1.5.4 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA roots{0.203} [Roots](roots-1.10.2-0.203.0 %282%29.jar) 
    UCHIJAAAAAAAAAAAAAA safejoin{1.3} [SafeJoin](SaveJoin-mc1.10.2-1.3.jar) 
    UCHIJAAAAAAAAAAAAAA SilentLib{1.0.12} [Silent Lib](SilentLib-1.9.4-1.0.12-20 %282%29.jar) 
    UCHIJAAAAAAAAAAAAAA scalinghealth{0.2.2} [Scaling Health](ScalingHealth-1.9.4-0.2.2-20 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA shetiphiancore{3.3.0} [ShetiPhian-Core](shetiphiancore-1.10.0-3.3.0.jar) 
    UCHIJAAAAAAAAAAAAAA soundfilters{0.9_for_1.9} [Sound Filters](SoundFilters-0.9_for_1.9.4 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA StorageDrawers{1.10.2-3.2.6} [Storage Drawers](StorageDrawers-1.10.2-3.2.6 %283%29.jar) 
    UCHIJAAAAAAAAAAAAAA structuredcrafting{0.1.6} [Structured Crafting](StructuredCrafting-1.9.4-0.1.6 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA surge{1.0.0.50} [Surge](Surge-1.10.2-1.0.0.50 %284%29.jar) 
    UCHIJAAAAAAAAAAAAAA totemic{1.9.4-0.7.8} [Totemic](Totemic-1.9.4-0.7.8 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA va{1.10.2-1.5} [Vanilla Automation](va-1.10.2-1.5 %282%29.jar) 
    UCHIJAAAAAAAAAAAAAA vending{1.3.4} [vending](vending-1.9.4-1.3.4.jar) 
    UCHIJAAAAAAAAAAAAAA waterstrainer{1.2.1} [Water Strainer](WaterStrainer-1.9.4-1.2.1 %281%29.jar) 
    UCHIJAAAAAAAAAAAAAA waystones{2.0.4} [Waystones](Waystones_1.10.2-2.0.4.jar) 
    UCHIJAAAAAAAAAAAAAA weaponcaseloot{4.0.1} [WeaponCaseLoot](weaponcaseloot-1.10.2-4.0.1.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (Bloodmoon-MC1.9.4-1.4.1.jar)
  lumien.bloodmoon.asm.ClassTransformer
SHLoadingPlugin (ScalingHealth-1.9.4-0.2.2-20 (1).jar)
  net.silentchaos512.scalinghealth.asm.SHClassTransformer
FMLPlugin (InventoryTweaks-1.61-58 (2).jar)
  invtweaks.forge.asm.ContainerTransformer
IvToolkit (IvToolkit-1.2.8.5.jar)

NWRTweak (redstonepaste-mc1.9.4-1.7.4 (2).jar)
  net.fybertech.nwr.NWRTransformer
LoadingPlugin (HardcoreDarkness-MC1.9.4-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
SurgeLoadingPlugin (Surge-1.10.2-1.0.0.50 (4).jar)
  net.epoxide.surge.asm.SurgeTransformerManager
BookshelfLoadingPlugin (Bookshelf-1.10.2-1.4.1.319.jar)
  net.darkhax.bookshelf.asm.BookshelfTransformerManager
ShetiPhian-ASM (shetiphiancore-1.10.0-3.3.0.jar)
  shetiphian.core.asm.ClassTransformer
dsurroundcore_unofficial (DynamicSurroundingsUnofficial-1.10.2-3.0.6.1BETA.jar)
  org.blockartistry.mod.DynSurround.asm.Transformer
    Pulsar/natura loaded Pulses: 
        - NaturaCommons (Enabled/Forced)
        - NaturaOverworld (Enabled/Not Forced)
        - NaturaNether (Enabled/Not Forced)
        - NaturaEntities (Enabled/Not Forced)
        - NaturaOredict (Enabled/Forced)
        - NaturaWorld (Enabled/Not Forced)

```
Profiler Position: N/A (disabled)
Player Count: 1 / 8; [EntityPlayerMP['<PROFILE NAME>'/7119, l='Silica', x=76.57, y=84.00, z=125.87]]
Type: Integrated Server (map_client.txt)
Is Modded: Definitely; Client brand changed to 'fml,forge'
```

[21:23:20] [Client thread/INFO]: [net.minecraft.init.Bootstrap:func_179870_a:560]: #@!@# Game crashed! Crash report saved to: #@!@# /Applications/MultiMC.app/Contents/MacOS/instances/Nylla/minecraft/crash-reports/crash-2016-09-26_21.23.20-server.txt
[21:23:20] [Client thread/INFO]: Waiting for the server to terminate/save.
[21:23:20] [Server thread/INFO]: <PROFILE NAME> lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}
[21:23:20] [Server thread/INFO]: <PROFILE NAME> left the game
[21:23:20] [Server thread/INFO]: Stopping singleplayer server as player logged out
[21:23:20] [Server thread/INFO]: Saving worlds
[21:23:20] [Server thread/INFO]: Saving chunks for level 'Silica'/Overworld
[21:23:21] [Server thread/INFO]: Saving chunks for level 'Silica'/Nether
[21:23:21] [Server thread/INFO]: Saving chunks for level 'Silica'/The End
[21:23:22] [Server thread/INFO]: Unloading dimension 0
[21:23:22] [Server thread/INFO]: Unloading dimension -1
[21:23:22] [Server thread/INFO]: Unloading dimension 1
[21:23:22] [Server thread/INFO]: Applying holder lookups
[21:23:22] [Server thread/INFO]: Holder lookups applied
[21:23:22] [Server thread/INFO]: The state engine was in incorrect state SERVER_STOPPING and forced into state SERVER_STOPPED. Errors may have been discarded.
[21:23:22] [Client thread/INFO]: Server terminated.
AL lib: (EE) alc_cleanup: 1 device not closed
Process exited with code 255.

**Comment by alexbegt** [comment]
What version of Natura do you have installed?

**Comment by davidgarland** [comment]
Latest 1.10 version from Curse Forge.

**Comment by alexbegt** [comment]
'natura-1.10.2-4.0.0.76' correct?

**Comment by davidgarland** [comment]
Correct.

**Comment by RealGrep** [comment]
Same exact error here as well while exploring. I'd paste the log (and can on request), but it's the error above exactly. natura-1.10.2-4.0.0.76.jar, of course, on Forge 2093.
