### ISSUE TITLE
Crash when disabling Overworld Generation in config

### ISSUE THREAD

**Issue by RiverC** [progwml6/Natura#312]
I've got a lot generating in the overworld, and together it was overwhelming the terrain generator. However, I still wanted the nether trees to generate.

However, when I set 

`B:NaturaOverworld=false`

In the modules config, this is what happens

```
java.lang.Error: java.lang.reflect.InvocationTargetException
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:89)
	... 33 more
Caused by: java.lang.NullPointerException
	at com.progwml6.natura.shared.NaturaCommons.registerRecipes(NaturaCommons.java:193)
	at com.progwml6.natura.shared.NaturaCommons.init(NaturaCommons.java:179)
	... 38 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:795)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 725562824 bytes (691 MB) / 1880891392 bytes (1793 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 63 mods loaded, 62 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHI	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHI	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHI	ivtoolkit{1.2.9} [IvToolkit] (minecraft.jar) 
	UCHI	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UCHI	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHI	ForgeEndertech{1.1.3.0} [Forge Endertech] (ForgeEndertech-1.10.2-1.1.3.0.jar) 
	UCHI	AdChimneys{1.10.2-1.1.4.0} [Advanced Chimneys] (AdChimneys-1.10.2-1.1.4.0.jar) 
	UCHI	architecturecraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.10.2.jar) 
	UCHI	Quark{r1.1-66} [Quark] (Quark-r1.1-66.jar) 
	UCHI	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHI	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4g.jar) 
	UCHI	betteragriculture{1.0.1} [Better Agriculture] (BetterAgriculture-[1.10.2]-1.0.1.jar) 
	UCHI	betterfoliage{2.1.3} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.3.jar) 
	UCHI	malisiscore{1.10.2-4.2.8} [MalisisCore] (malisiscore-1.10.2-4.2.8.jar) 
	UCHI	malisisdoors{1.10.2-5.1.5} [MalisisDoors] (malisisdoors-1.10.2-5.1.5.jar) 
	UCHI	bigdoors{1.10.2-1.3.0} [Big Doors] (BigDoors-1.10.2-1.3.0.jar) 
	UCHI	BiomeTweaker{2.1.229} [BiomeTweaker] (BiomeTweaker-1.10.2-2.1.229.jar) 
	UCHI	BiomesOPlenty{5.0.0.2091} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2091-universal.jar) 
	UCHI	infinitylib{1.10.2-0.3.0} [InfinityLib] (infinitylib-0.3.0.jar) 
	UCHI	boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull] (boatifull-0.3.0.jar) 
	UCHI	CodeChickenLib{2.5.0.178} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UCHI	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHI	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHI	dsurround{3.1.2.0BETA} [Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.1.2.0BETA.jar) 
	UCHI	Earthworks{0.0.6} [Earthworks] (Earthworks-0.0.6.jar) 
	UCHI	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHI	JEI{3.13.6.387} [Just Enough Items] (jei_1.10.2-3.13.6.387.jar) 
	UCHI	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.2.3.jar) 
	UCHI	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.2.4.jar) 
	UCHI	geographicraft{0.8.2} [GeographiCraft] (GeographiCraft-0.8.3.jar) 
	UCHI	glasscraftmod{2.0} [Glasscraft] (Glasscraftmod v1.01 - MC1.10.2 Forge.jar) 
	UCHI	gravestone{1.5.9} [Gravestone] (GraveStone Mod 1.5.9.jar) 
	UCHI	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHI	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHI	immersiveengineering{0.10-53} [Immersive Engineering] (ImmersiveEngineering-0.10-53.jar) 
	UCHI	journeymap{1.10.2-5.3.1} [JourneyMap] (journeymap-1.10.2-5.3.1.jar) 
	UCHI	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHI	malisisblocks{1.10.2-4.1.3} [Malisis Blocks] (malisisblocks-1.10.2-4.1.3.jar) 
	UCHI	missing_pieces{4.1.1} [Missing Pieces] (missing_pieces-1.10.2-4.1.1.jar) 
	UCHI	morematerials{1.10.2-1.9.20160723.0} [More Materials] (morematerials-1.10.2-1.9.20160723.0.jar) 
	UCHI	Morpheus{1.10.2-3.1.7} [Morpheus] (Morpheus-1.10.2-3.1.7.jar) 
	UCHI	shetiphiancore{3.3.5} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.5.jar) 
	UCHI	multibeds{1.2.3} [Multi-Beds] (multibeds-1.10.0-1.2.3.jar) 
	UCHI	multistorage{1.2.12} [Multi-Storage] (multistorage-1.10.0-1.2.12.jar) 
	UCH	natura{1.10.2-4.0.0.93} [Natura] (natura-1.10.2-4.0.0.93.jar) 
	UCH	nethercore{1.10.2-2.0.3} [Nether Core] (nethercore-1.10.2-2.0.3.jar) 
	UCH	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCH	platforms{1.2.6} [Platforms] (platforms-1.10.0-1.2.6.jar) 
	UCH	precisetime{1.0.0} [Precise Time] (PreciseTime1.0b.jar) 
	UCH	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCH	reccomplex{1.2.4} [Recurrent Complex] (RecurrentComplex-1.2.4.jar) 
	UCH	reliquia{0.0.6} [Reliquia] (Reliquia-[1.10.2]-0.0.6.jar) 
	UCH	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCH	RTG{4.1.2.0} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.0.jar) 
	UCH	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UCH	supercraftingframe{1.2.1.87} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.1.87.jar) 
	UCH	taiga{1.2.2} [Tinkers Alloying Addon] (taiga-1.10.2-1.2.2.jar) 
	UCH	undergroundbiomes{0.9.beta.8} [Underground Biomes] (UndergroundBiomesConstructs-1.10-0.9-beta.11.jar) 
	UCH	vc{v4.0.2a-mc1.10.2} [ViesCraft] (ViesCraft-4.0.2a-mc1.10.2.jar) 
	UCH	vd{v1.0a-mc1.10.2} [Viesis' Dismounter] (Viesis' Dismount-1.0a-mc1.10.2.jar) 
	UCH	wtfcore{1.10.2_v1.1} [Wtfs Expedition] (WTF-Expedition_1.10.2_v1.3.jar) 
	UD	BiomeTweakerCore{2.1.229} [BiomeTweaker Core] (minecraft.jar) 
```

**Comment by Viatos** [comment]
This also happens when you disable the creature generation. My suspicion is actually disabling any of those features leads to this crash.

**Comment by alexbegt** [comment]
Once natura-1.10.2-4.1.0.15 goes live on CurseForge, It has the fix in it.

**Comment by RiverC** [comment]
Same issue, but seems like it happens at the end of init. Note: I have just overworld disabled. I bolded where the issue is, I believe.

Time: 12/27/16 10:16 PM
Description: Initializing game

```
java.lang.Error: java.lang.reflect.InvocationTargetException
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:800)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:89)
	... 33 more
**Caused by: java.lang.ExceptionInInitializerError
	at com.progwml6.natura.world.NaturaWorld.postInit(NaturaWorld.java:48)
	... 38 more
Caused by: java.lang.NullPointerException
	at com.progwml6.natura.world.worldgen.TreeGenerator.<init>(TreeGenerator.java:54)
	at com.progwml6.natura.world.worldgen.TreeGenerator.<clinit>(TreeGenerator.java:34)**
	... 39 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at slimeknights.mantle.pulsar.internal.BusExceptionHandler.handle(BusExceptionHandler.java:30)
	at slimeknights.mantle.pulsar.flightpath.Flightpath.post(Flightpath.java:92)
	at slimeknights.mantle.pulsar.control.PulseManager.propagateEvent(PulseManager.java:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:243)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:221)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:145)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:800)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:324)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:520)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 883549936 bytes (842 MB) / 2108432384 bytes (2010 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2185 64 mods loaded, 63 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJ	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJ	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJ	Forge{12.18.3.2185} [Minecraft Forge] (forge-1.10.2-12.18.3.2185.jar) 
	UCHIJ	ivtoolkit{1.2.9} [IvToolkit] (minecraft.jar) 
	UCHIJ	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UCHIJ	mercurius_updater{1.0} [mercurius_updater] (MercuriusUpdater-1.10.2.jar) 
	UCHIJ	ForgeEndertech{1.1.3.0} [Forge Endertech] (ForgeEndertech-1.10.2-1.1.3.0.jar) 
	UCHIJ	AdChimneys{1.10.2-1.1.4.0} [Advanced Chimneys] (AdChimneys-1.10.2-1.1.4.0.jar) 
	UCHIJ	architecturecraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.10.2.jar) 
	UCHIJ	Quark{r1.1-68} [Quark] (Quark-r1.1-68.jar) 
	UCHIJ	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJ	bagginses{2.4.2d} [Bagginses] (Bagginses-1.10.2-3.0.4g.jar) 
	UCHIJ	betteragriculture{1.0.1} [Better Agriculture] (BetterAgriculture-[1.10.2]-1.0.1.jar) 
	UCHIJ	betterfoliage{2.1.3} [Better Foliage] (BetterFoliage-MC1.10.2-2.1.3.jar) 
	UCHIJ	malisiscore{1.10.2-4.2.8} [MalisisCore] (malisiscore-1.10.2-4.2.8.jar) 
	UCHIJ	malisisdoors{1.10.2-5.1.5} [MalisisDoors] (malisisdoors-1.10.2-5.1.5.jar) 
	UCHIJ	bigdoors{1.10.2-1.3.0} [Big Doors] (BigDoors-1.10.2-1.3.0.jar) 
	UCHIJ	BiomeTweaker{2.1.229} [BiomeTweaker] (BiomeTweaker-1.10.2-2.1.229.jar) 
	UCHIJ	BiomesOPlenty{5.0.0.2091} [Biomes O' Plenty] (BiomesOPlenty-1.10.2-5.0.0.2091-universal.jar) 
	UCHIJ	infinitylib{1.10.2-0.3.0} [InfinityLib] (infinitylib-0.3.0.jar) 
	UCHIJ	boatifull{@MAJOR@.@MINOR@.@REVIS@} [Boatifull] (boatifull-0.4.0.jar) 
	UCHIJ	CodeChickenLib{2.5.0.178} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.0.178-universal.jar) 
	UCHIJ	MineTweaker3{3.0.13} [MineTweaker 3] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJ	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.10.2-3.0.13.jar) 
	UCHIJ	dsurround{3.1.3.0BETA} [Dynamic Surroundings] (DynamicSurroundings-1.10.2-3.1.3.0BETA.jar) 
	UCHIJ	Earthworks{0.0.6} [Earthworks] (Earthworks-0.0.6.jar) 
	UCHIJ	fastleafdecay{v11} [Fast Leaf Decay] (FastLeafDecay-v11.jar) 
	UCHIJ	JEI{3.13.6.393} [Just Enough Items] (jei_1.10.2-3.13.6.393.jar) 
	UCHIJ	ftbl{0.0.0} [FTBLib] (FTBLib-1.10.2-3.2.3.jar) 
	UCHIJ	ftbu{0.0.0} [FTBUtilities] (FTBUtilities-1.10.2-3.2.4.jar) 
	UCHIJ	geographicraft{0.8.2} [GeographiCraft] (GeographiCraft-0.8.3.jar) 
	UCHIJ	glasscraftmod{2.0} [Glasscraft] (Glasscraftmod v1.01 - MC1.10.2 Forge.jar) 
	UCHIJ	gravestone{1.5.10} [Gravestone] (GraveStone Mod 1.5.10.jar) 
	UCHIJ	mantle{1.10.2-1.1.3.199} [Mantle] (Mantle-1.10.2-1.1.3.jar) 
	UCHIJ	tconstruct{1.10.2-2.6.1.464} [Tinkers' Construct] (TConstruct-1.10.2-2.6.1.jar) 
	UCHIJ	immersiveengineering{0.10-54} [Immersive Engineering] (ImmersiveEngineering-0.10-54.jar) 
	UCHIJ	journeymap{1.10.2-5.3.1} [JourneyMap] (journeymap-1.10.2-5.3.1.jar) 
	UCHIJ	jeresources{0.5.8.98} [Just Enough Resources] (JustEnoughResources-1.10.2-0.5.8.98.jar) 
	UCHIJ	malisisblocks{1.10.2-4.1.3} [Malisis Blocks] (malisisblocks-1.10.2-4.1.3.jar) 
	UCHIJ	missing_pieces{4.1.1} [Missing Pieces] (missing_pieces-1.10.2-4.1.1.jar) 
	UCHIJ	morematerials{1.10.2-1.9.20160723.0} [More Materials] (morematerials-1.10.2-1.9.20160723.0.jar) 
	UCHIJ	Morpheus{1.10.2-3.1.7} [Morpheus] (Morpheus-1.10.2-3.1.7.jar) 
	UCHIJ	shetiphiancore{3.3.5} [ShetiPhian-Core] (shetiphiancore-1.10.0-3.3.5.jar) 
	UCHIJ	multibeds{1.2.3} [Multi-Beds] (multibeds-1.10.0-1.2.3.jar) 
	UCHIJ	multistorage{1.2.12} [Multi-Storage] (multistorage-1.10.0-1.2.12.jar) 
	UCHI	natura{1.10.2-4.1.0.15} [Natura] (natura-1.10.2-4.1.0.15.jar) 
	UCHI	nethercore{1.10.2-2.0.3} [Nether Core] (nethercore-1.10.2-2.0.3.jar) 
	UCHI	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHI	platforms{1.2.6} [Platforms] (platforms-1.10.0-1.2.6.jar) 
	UCHI	railcraft{10.0.1} [Railcraft] (Railcraft_1.10.2-10.0.1.jar) 
	UCHI	reccomplex{1.2.4} [Recurrent Complex] (RecurrentComplex-1.2.4.jar) 
	UCHI	reliquia{0.0.6} [Reliquia] (Reliquia-[1.10.2]-0.0.6.jar) 
	UCHI	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UCHI	RTG{4.1.2.1} [Realistic Terrain Generation] (RTG-1.10.2-4.1.2.1.jar) 
	UCHI	simpleretrogen{4.0.1+8} [Simple Retrogen] (simpleretrogen-1.10-4.0.1+8.jar) 
	UCHI	supercraftingframe{1.2.1.87} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.1.87.jar) 
	UCHI	taiga{1.2.2} [Tinkers Alloying Addon] (taiga-1.10.2-1.2.2.jar) 
	UCHI	undergroundbiomes{0.9.beta.8} [Underground Biomes] (UndergroundBiomesConstructs-1.10-0.9-beta.11.jar) 
	UCHI	vc{v4.0.2a-mc1.10.2} [ViesCraft] (ViesCraft-4.0.2a-mc1.10.2.jar) 
	UCHI	vd{v1.0a-mc1.10.2} [Viesis' Dismounter] (Viesis' Dismount-1.0a-mc1.10.2.jar) 
	UCHI	examplemod{1.0} [examplemod] (WTF-Expedition_1.10.2_v1.3Beta7.jar) 
	UCHI	wtfcore{1.10.2_v1.1} [Wtfs Expedition] (WTF-Expedition_1.10.2_v1.3Beta7.jar) 
	UCHI	B3M{1.9.4-04} [???????? ????? ?????????????] (?????????????-1.9.4.jar) 
	UD	BiomeTweakerCore{2.1.229} [BiomeTweaker Core] (minecraft.jar) 
```

**Comment by alexbegt** [comment]
Once natura-1.10.2-4.1.0.17 goes live on CurseForge, this bug will be fixed @RiverC .
