### ISSUE TITLE
[1.10.2] Crash when right clicking Sulfur Cloud

### ISSUE THREAD

**Issue by Pythonic-Rainbow** [progwml6/Natura#388]
`java.lang.NullPointerException: Unexpected error
	at com.progwml6.natura.shared.block.clouds.BlockCloud.func_180639_a(BlockCloud.java:70)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:410)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1749)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1055)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)`

`-- Head --
Thread: Client thread
Stacktrace:
	at com.progwml6.natura.shared.block.clouds.BlockCloud.func_180639_a(BlockCloud.java:70)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187099_a(PlayerControllerMP.java:410)
	at PlayerControllerOF.func_187099_a(PlayerControllerOF.java:88)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1518)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2184)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:1961)`

**Comment by ChaoticNonsense** [comment]
Came here to post exactly this issue.  I'm running the most recent Sky Factory 3, and can replicate this crash every time. Server runs fine, but the client crashes to desktop.

**Comment by Pythonic-Rainbow** [comment]
My friend crashes 4 times because of it so we eventually removed the cloud in our home

**Comment by alexbegt** [comment]
What version of minecraft are you running?
